service: serverless-ts-app

plugins:
  - serverless-plugin-typescript
  - serverless-offline

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  createUser:
    handler: src/api.createUser
    events:
      - http:
          path: user
          method: post

custom:
  dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: "8080"
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
