service: serverless-ts-app

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  listUsers:
    handler: src/api.listUsers
    events:
      - http:
          path: /users
          method: get
  createUser:
    handler: src/api.createUser
    events:
      - http:
          path: /users
          method: post

custom:
  dotenv:
    logging: false
  serverless-offline:
    printOutput: false
